version: "3.8"

services:
  app:
    image: ${IMAGE_NAME}
    environment:
      - API_URL=${API_URL}
      - API_TOKEN=${API_TOKEN}
    restart: always
    container_name: next-dev
    ports:
      - 3000:3000
    deploy:
      mode: replicated
      replicas: 2
